# This is a basic workflow to help you get started with Actions

name: CI with Java anad Gradle

# Controls when the action will run. 
on: [push]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Setup JDK 11
        uses: actions/setup-java@V2
        with:
          java-vserion: '11'
          distribution: 'adopt'
      
      - name: Checkout our Code
        uses: actions/checkout@v2
        
        # need to make gradle wrapper executable
      - name: Make gradle executable
        run: chmod +x ./gradlew
    
      - name: Build with Gradle 
        run: ./gradlew build
